### ISSUE TITLE
Working with page builder plugins

### ISSUE THREAD

**Issue by mizejewski** [bu-ist/bu-versions#23]
Any plans for BU Versions to work on a site that is also using a page builder plugin like Beaver Builder or Divi Builder? Your plug-in is simple and exactly what I need, but it won't work because I'm also using the very popular Beaver Builder.

**Comment by grcwordpress** [comment]
For Divi/Divi builder, you can update your functions.php file to add the custom post type you want the builder to support. **But is the BU "alternate" version a custom post type?** 

e.g., 

function my_et_builder_post_types( $post_types ) {
    $post_types[] = 'YOUR_CPT_HERE';
    $post_types[] = 'ANOTHER_CPT_HERE';
     
    return $post_types;
}
add_filter( 'et_builder_post_types', 'my_et_builder_post_types' );

[Reference on Elegant Themes website](https://www.elegantthemes.com/blog/divi-resources/how-to-add-the-divi-builder-to-custom-post-types-divi-nation-short).

**Comment by inderpreet99** [comment]
The BU "alternate" version is a custom post type.

The alternate post type name is generated using the first 14 letters of the post type name and then appending the "_alt" string at the end. If there is a naming collision (highly unlikely), there will be numbers incremented before the "_alt" string. You can get the exact post type name by watching the `bu_alt_versions_post_type_alt_name` filter hook.

Examples:
```
page => page_alt
custom_pt => custom_pt_alt
```
